name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests (if any)
        run: |
          # ./build/tests/your_test_binary
          echo "No tests specified"
